// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ztm_demo

import (
	"github.com/zutim/ztm-demo/common/apis"
	"github.com/zutim/ztm-demo/internal/order/data"
	service2 "github.com/zutim/ztm-demo/internal/order/service"
	"github.com/zutim/ztm-demo/internal/user/service"
)

// Injectors from wire.go:

func InitApis() *apis.Api {
	userServer := service.NewUserService()
	orderRepo := data.NewOrderData()
	orderServer := service2.NewOrderService(orderRepo)
	api := apis.NewApis(userServer, orderServer)
	return api
}
